/**
 * Reading the backup settings, and building the commands they imply (§11).
 *
 * Pure on purpose. Everything here is a string in and a string out — no
 * spawning, no filesystem, no network — so the part of a backup that is easiest
 * to get quietly wrong (an argument list nobody reads until the restore) is
 * covered by unit tests that need neither borg nor a storage box.
 *
 * The split between the two prefixes is worth knowing:
 *
 *   BORG_*    variables borg itself reads. They are passed to the child
 *             process untouched, so anything documented by borg works here.
 *   BACKUP_*  this app's own settings — when to run, what to keep, which key
 *             to connect with.
 *
 * Targets borg 1.2–1.4 (`borg init`, `--glob-archives`). Borg 2 renamed both;
 * src/lib/borgError.ts recognises what that failure looks like and says so.
 */

import {
  DEFAULT_BACKUP_SCHEDULE,
  type BackupSchedule,
  parseBackupSchedule,
} from "./backupSchedule.ts";

/**
 * Every archive this app writes is named with this prefix, and prune only ever
 * considers archives matching it. A borg repository can hold more than one
 * thing's backups; nothing here should be able to delete something it didn't
 * create.
 */
export const ARCHIVE_PREFIX = "mealplanner-";

/** The name of the dump inside the archive — and so the name you restore from. */
export const DUMP_NAME = "mealplanner.sql";

/**
 * Where the key and borg's cache live by default.
 *
 * Both must outlive the container: the key because the storage box has been
 * told to trust it, and the cache because without it borg re-reads the whole
 * repository to work out what's already there — turning a nightly two-second
 * upload into a full download.
 */
export const DEFAULT_STATE_DIR = "/var/lib/mealplanner";

export interface BorgRetention {
  daily: number;
  weekly: number;
  monthly: number;
}

/**
 * A week of nights, a month of weeks, half a year of months — about 17
 * archives, which on a deduplicated repository costs little more than the one.
 * Long enough that a corruption noticed a fortnight late is still recoverable.
 */
export const DEFAULT_RETENTION: BorgRetention = { daily: 7, weekly: 4, monthly: 6 };

export interface BorgConfig {
  /** e.g. ssh://u12345@u12345.your-storagebox.de:23/./mealplanner */
  repo: string;
  /** Encrypts the repository. Without it the archives are unreadable — see readBorgConfig. */
  passphrase: string;
  /** Private key used for the ssh:// transport; generated by the app if absent. */
  sshKeyPath: string;
  /** BORG_BASE_DIR — borg's cache, config and security state. */
  baseDir: string;
  retention: BorgRetention;
  schedule: BackupSchedule;
  /** False when BACKUP_SCHEDULER=off: run by hand only. */
  schedulerEnabled: boolean;
}

export interface ReadBorgConfig {
  config: BorgConfig;
  /** Required settings with no value. Empty means the app can back up. */
  missing: string[];
  /** Values that were present but unusable; each fell back to its default. */
  problems: string[];
}

function positiveInt(raw: string | undefined, fallback: number, name: string, problems: string[]): number {
  const trimmed = raw?.trim();
  if (!trimmed) return fallback;
  const value = Number(trimmed);
  if (!Number.isInteger(value) || value < 0) {
    problems.push(`${name}="${trimmed}" is not a whole number of archives to keep; using ${fallback}.`);
    return fallback;
  }
  return value;
}

/**
 * The backup settings, and what's stopping them working.
 *
 * Never throws and never returns null: a half-configured instance still has to
 * render a settings screen that explains itself, which means the config object
 * has to survive being incomplete. `missing` is what the screen shows.
 *
 * Note what is *not* here: the passphrase is read from the environment and
 * never written to the database. It has to be recoverable when the database is
 * gone — that being the situation backups exist for — so keeping it inside the
 * thing being backed up would make every archive unreadable exactly when it
 * mattered.
 */
export function readBorgConfig(env: NodeJS.ProcessEnv = process.env): ReadBorgConfig {
  const problems: string[] = [];

  const repo = env.BORG_REPO?.trim() ?? "";
  const passphrase = env.BORG_PASSPHRASE ?? "";

  const missing: string[] = [];
  if (!repo) missing.push("BORG_REPO");
  if (!passphrase) missing.push("BORG_PASSPHRASE");

  const { schedule, problems: scheduleProblems } = parseBackupSchedule({
    hour: env.BACKUP_HOUR,
    // TZ is what the rest of the container's local times follow, so honour it
    // before falling back to the default zone.
    timeZone: env.BACKUP_TIMEZONE ?? env.TZ,
  });
  problems.push(...scheduleProblems);

  const stateDir = env.BACKUP_STATE_DIR?.trim() || DEFAULT_STATE_DIR;

  return {
    config: {
      repo,
      passphrase,
      sshKeyPath: env.BACKUP_SSH_KEY?.trim() || `${stateDir}/ssh/id_ed25519`,
      baseDir: env.BORG_BASE_DIR?.trim() || `${stateDir}/borg`,
      retention: {
        daily: positiveInt(env.BACKUP_KEEP_DAILY, DEFAULT_RETENTION.daily, "BACKUP_KEEP_DAILY", problems),
        weekly: positiveInt(env.BACKUP_KEEP_WEEKLY, DEFAULT_RETENTION.weekly, "BACKUP_KEEP_WEEKLY", problems),
        monthly: positiveInt(env.BACKUP_KEEP_MONTHLY, DEFAULT_RETENTION.monthly, "BACKUP_KEEP_MONTHLY", problems),
      },
      schedule,
      schedulerEnabled: env.BACKUP_SCHEDULER?.trim().toLowerCase() !== "off",
    },
    missing,
    problems,
  };
}

/** Whether a backup can be attempted at all. */
export function isBackupConfigured(env: NodeJS.ProcessEnv = process.env): boolean {
  return readBorgConfig(env).missing.length === 0;
}

export interface RepoDescription {
  kind: "ssh" | "local";
  /** Safe to show on screen and put in logs — a repo URL carries no secret. */
  display: string;
  user?: string;
  host?: string;
  port?: number;
  path?: string;
  /** Set when the string doesn't parse as either form. */
  problem?: string;
}

/**
 * What a repository string points at.
 *
 * The settings screen uses this to say "u12345@u12345.your-storagebox.de" in
 * the sentence about installing the SSH key, and to notice the two mistakes
 * that account for most first-time failures: a Hetzner Storage Box needs an
 * explicit port 23, and its paths are relative (`/./mealplanner`) rather than
 * absolute.
 */
export function describeRepo(repo: string): RepoDescription {
  const trimmed = repo.trim();
  if (!trimmed) return { kind: "local", display: "", problem: "No repository is set." };

  if (!trimmed.startsWith("ssh://")) {
    if (trimmed.includes("@") && trimmed.includes(":")) {
      return {
        kind: "local",
        display: trimmed,
        problem:
          "This looks like an scp-style address. Borg wants a URL here: ssh://user@host:port/./path.",
      };
    }
    return { kind: "local", display: trimmed, path: trimmed };
  }

  let url: URL;
  try {
    url = new URL(trimmed);
  } catch {
    return { kind: "ssh", display: trimmed, problem: "This isn't a URL borg can parse." };
  }

  const port = url.port ? Number(url.port) : undefined;

  // The path is taken from the string rather than from `url.pathname`, because
  // the URL parser normalises away the single-dot segment — and that segment is
  // the whole difference between a path under the login's home directory
  // (`/./mealplanner`) and one at the root of the filesystem (`/mealplanner`).
  // Reading the parsed form would report the two as identical and quietly hide
  // the mistake this function exists to catch.
  const afterScheme = trimmed.slice("ssh://".length);
  const firstSlash = afterScheme.indexOf("/");
  const path = firstSlash === -1 ? "" : afterScheme.slice(firstSlash);

  const description: RepoDescription = {
    kind: "ssh",
    display: trimmed,
    user: decodeURIComponent(url.username) || undefined,
    host: url.hostname,
    port,
    path,
  };

  if (url.hostname.endsWith(".your-storagebox.de") && port !== 23) {
    description.problem =
      "A Hetzner Storage Box listens for SSH on port 23, not 22. Add :23 after the hostname.";
  } else if (url.hostname.endsWith(".your-storagebox.de") && !path.startsWith("/./")) {
    description.problem =
      "A Storage Box path is relative to your home directory: use /./mealplanner rather than /mealplanner.";
  }

  return description;
}

/**
 * The ssh command borg shells out to (BORG_RSH).
 *
 * `BatchMode=yes` because there is no terminal to answer a prompt on: without
 * it a missing key hangs the backup on a password prompt until the timeout
 * rather than failing with something worth reading.
 *
 * `accept-new` trusts the host key the first time and pins it after, which is
 * the trade every unattended backup makes. The alternative — `yes` — means the
 * first backup on a rebuilt box fails until someone runs ssh by hand in the
 * container, and `no` means a man-in-the-middle is as welcome as the real
 * host. A changed key still stops the backup dead, which is the part that
 * matters.
 */
export function sshCommand(config: BorgConfig): string {
  return [
    "ssh",
    "-i",
    config.sshKeyPath,
    "-o",
    "BatchMode=yes",
    "-o",
    "StrictHostKeyChecking=accept-new",
    // Beside the key, in the volume — not under $HOME, which in a container is
    // wiped on every rebuild. A known_hosts that doesn't survive a restart
    // makes `accept-new` re-trust whatever answers, every time, which is the
    // same as not checking at all.
    "-o",
    `UserKnownHostsFile=${knownHostsPath(config)}`,
  ].join(" ");
}

/** known_hosts beside the private key, so both live in the same volume. */
export function knownHostsPath(config: BorgConfig): string {
  return config.sshKeyPath.replace(/\/[^/]*$/, "/known_hosts");
}

/**
 * The environment a borg child process runs with.
 *
 * The passphrase travels in the environment rather than on the command line,
 * where `ps` would show it to anything else on the box.
 */
export function borgEnv(config: BorgConfig): Record<string, string> {
  return {
    BORG_REPO: config.repo,
    BORG_PASSPHRASE: config.passphrase,
    BORG_RSH: sshCommand(config),
    BORG_BASE_DIR: config.baseDir,
    // Every prompt borg can raise, answered in advance. Each of these is a
    // question asked on a terminal that doesn't exist here; unanswered, they
    // hang the nightly run instead of failing it.
    BORG_RELOCATED_REPO_ACCESS_IS_OK: "no",
    BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK: "no",
    BORG_CHECK_I_KNOW_WHAT_I_AM_DOING: "NO",
    BORG_DELETE_I_KNOW_WHAT_I_AM_DOING: "NO",
    BORG_EXIT_CODES: "modern",
  };
}

/** `mealplanner-2026-08-30T01-00-00Z` — sorts chronologically, safe in a shell. */
export function archiveName(now: Date): string {
  return `${ARCHIVE_PREFIX}${now.toISOString().replace(/\.\d{3}Z$/, "Z").replace(/:/g, "-")}`;
}

/**
 * `borg init` — a repokey repository.
 *
 * `repokey-blake2` keeps the encryption key in the repository itself, unlocked
 * by the passphrase. The alternative, `keyfile`, keeps it on this box, which
 * means the box burning down takes the only key to the backups with it. With
 * repokey the passphrase alone restores, from anywhere.
 */
export function initArgs(config: BorgConfig): string[] {
  return ["init", "--encryption=repokey-blake2", config.repo];
}

/**
 * `borg create` reading the dump from stdin.
 *
 * Streamed rather than staged: the alternative is a temp file the size of the
 * database on a box whose disk is the thing being hedged against.
 *
 * Deliberately *not* gzipped on the way in, which is where scripts/backup.sh
 * had it wrong. Borg deduplicates by content-defined chunking, and gzip turns
 * a one-row change into a different byte stream from there on — so a
 * pre-compressed dump stores a fresh copy every night. Handing borg the plain
 * SQL lets it store the difference, and `--compression zstd` compresses the
 * chunks anyway.
 */
export function createArgs(config: BorgConfig, archive: string): string[] {
  return [
    "create",
    "--json",
    "--compression",
    "zstd",
    "--lock-wait",
    "60",
    "--stdin-name",
    DUMP_NAME,
    `${config.repo}::${archive}`,
    "-",
  ];
}

/** `borg prune` — retention, restricted to archives this app wrote. */
export function pruneArgs(config: BorgConfig): string[] {
  return [
    "prune",
    "--lock-wait",
    "60",
    "--glob-archives",
    `${ARCHIVE_PREFIX}*`,
    `--keep-daily=${config.retention.daily}`,
    `--keep-weekly=${config.retention.weekly}`,
    `--keep-monthly=${config.retention.monthly}`,
    config.repo,
  ];
}

/**
 * `borg compact` — actually free what prune dropped.
 *
 * Since borg 1.2 prune only unlinks archives; the space comes back when the
 * segments are compacted. Skipping this is why a repository that "prunes
 * nightly" can still grow forever.
 */
export function compactArgs(config: BorgConfig): string[] {
  return ["compact", "--lock-wait", "60", config.repo];
}

/**
 * `borg delete` — remove one archive.
 *
 * Used for exactly one thing: taking back an archive whose dump turned out to
 * be truncated (see runBackup in src/lib/borg.ts). Never offered as a feature,
 * because "delete a backup" is not a button this app needs to have.
 */
export function deleteArchiveArgs(config: BorgConfig, archive: string): string[] {
  return ["delete", "--lock-wait", "60", `${config.repo}::${archive}`];
}

/** `borg list` — the archives, newest last, as JSON. */
export function listArgs(config: BorgConfig, last = 20): string[] {
  return ["list", "--json", "--glob-archives", `${ARCHIVE_PREFIX}*`, "--last", String(last), config.repo];
}

/** `borg info` — repository totals, and the cheapest proof that it can be reached. */
export function infoArgs(config: BorgConfig): string[] {
  return ["info", "--json", "--lock-wait", "10", config.repo];
}

/**
 * The commands that put the database back, for showing on screen.
 *
 * Restore instructions that live only in someone's head are the other half of
 * a backup that silently stopped: the archives are fine and nobody knows the
 * incantation. These run from the host against the compose stack, and go
 * through the app container because that is where borg, the SSH key and the
 * repository settings already are — the same reason `docker compose exec app
 * borg list` works with no arguments.
 *
 * The other case — the box itself is gone — needs no commands from here, but
 * it does need two things that must be written down somewhere off the box: the
 * repository passphrase, and a way to log in to the storage box now that the
 * key is ashes (for a Hetzner Storage Box, the account password). With those,
 * borg on any machine reads the archives.
 */
export function restoreCommands(archive = `${ARCHIVE_PREFIX}…`): string[] {
  return [
    "docker compose exec app borg list",
    `docker compose exec app borg extract --stdout ::${archive} ${DUMP_NAME} > mealplanner.sql`,
    "docker compose exec -T db psql -U mealplanner -d mealplanner < mealplanner.sql",
  ];
}
